### PR TITLE
Private methods cannot be final as they are never overridden by other classes

### PR DESCRIPTION
**Pull request by leocavalcante**
https://wiki.php.net/rfc/inheritance_private_methods

### CODE REVIEW

**Comment by kiss291323003** [comment]
thanks , by the way . are you use easyswoole now ? would you like to help us make easyswoole better

**Comment by leocavalcante** [comment]
Hi, no problem. I'm actually using https://github.com/easy-swoole/kafka, but sure I can help! Thanks for those packages.

**Comment by kiss291323003** [comment]
It seem's that you are working in PicPay at Brazil ，am I right ？  can you give me any ways to cantact to you , such as email or QQ ?

**Comment by leocavalcante** [comment]
You can find me at lc@leocavalcante.com and I'm also at the Swoole Slack group, just joined the #easyswoole channel.

**Pull request merged**
